name: MERN Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Build React App
    - name: Install and build frontend
      working-directory: ./client
      run: |
        npm install
        npm run build

    - name: Debug AWS Secrets (sanitized)
      run: |
        echo "ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "SECRET_KEY_LENGTH=${{ secrets.AWS_SECRET_ACCESS_KEY != '' && 'OK' || 'EMPTY' }}"

    - name: Test AWS credentials
      run: aws sts get-caller-identity
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1


    # Deploy to S3
    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: digital-invoice-react-app
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1
        SOURCE_DIR: client/build



    # SSH into EC2 and deploy backend
    - name: Deploy backend to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ${{ secrets.EC2_PATH }}
          git pull origin deploy
          npm install
          pm2 restart all
